### ISSUE TITLE
敬请期待

### ISSUE THREAD

**Issue by aisdn** [EndlessSora/DeeperForensics-1.0#1]
啥时候才能真正发布出来呀？要是过年的时候开放下载，那我这年都过不踏实了。。。。哈

**Comment by EndlessSora** [comment]
Thank you for your attention! We're still preparing our dataset, and will release it soon in the very near future. Currently, I cannot decide when to release the dataset due to some approval process. But I believe it will be soon. Once it is ready, we will make notification in this GitHub repository.

Wish you a happy Chinese New Year in advance! :)

**Comment by brunodoamaral** [comment]
Any update on this thread? Thanks!

**Comment by EndlessSora** [comment]
> Any update on this thread? Thanks!

We consider it necessary to be adequately prepared for such a dataset. Please be patient. We will try to make it ready soon. Thanks for your understanding.  :)

**Comment by puppet101** [comment]
By the way, will you release the code for your manipulation method  simultaneously?
