### ISSUE TITLE
Datasets split for stand, and training 

### ISSUE THREAD

**Issue by depblack** [EndlessSora/DeeperForensics-1.0#10]
Hi, thank you for your work. 
According to your paper, the standard set only includes 1k Youtube videos and 1k manipulated videos(end_to_end), right?
And if one wants to train their model on "std+std/sing", he or she need to apply the same pertubation on real videos(1k from ff++ and 100 actors' videos) , since the provided real videos have no pertubations, right?

Looking forward to your reply

**Comment by EndlessSora** [comment]
Thanks for your interest in our work.
1. Yes. The standard set only includes 1k Youtube videos and 1k manipulated videos (end_to_end).
2. Almost correct. The perturbations with a similar distribution should be applied to the real (1k Youtube videos from ff++, *but no need for 100 actors' videos* since they are source videos used for face manipulation) and fake videos if one would like to train his model on "std+std/sing".

**Comment by depblack** [comment]
Thanks! Very Quick reply

**Comment by depblack** [comment]
Sorry for having another similar question to bother you. 
Just like【And if one wants to train their model on "std+std/sing"】, if one wants to test their model on "std/sing", means testing on 5k manipulated videos and what?  (I know train:val:test is 7:1:2)

No1.  1k original Youtube videos , test part
No2.  5k Youtube videos (with the same pertubations, e.g. 000_M101.mp4 BW:3 -> 000.mp4 BW:3), test part.
 And the "000.mp4" will have 5 types.
No3.  6k Youtube videos from both No1 and No2, test part
No4.  just manipulated videos, no manipulated videos
I guess the answer is No2, right?
