### ISSUE TITLE
About std/x dataset in  your experiments in the paper

### ISSUE THREAD

**Issue by liquor233** [EndlessSora/DeeperForensics-1.0#4]
hi!
Thank you for your wonderful work~ 
I have noticed that you have used different data settings in your experiments: std/sing 、std/rand 、std/mix, and I am confused that whether you add the same perturbations to the original video data as you did to the manipulated data in the experiments?

**Comment by EndlessSora** [comment]
Yes. The same perturbations/perturbations with a same distribution were applied to the original videos (i.e., target videos).

**Comment by liquor233** [comment]
Thank you for your quick reply!
By the way, Could you please tell me where can I find your hidden test set? have you released it yet or have you built a website where I can test my model on your hidden set?

**Comment by EndlessSora** [comment]
We do not plan to release the hidden test set due to our challenge plan (see https://github.com/EndlessSora/DeeperForensics-1.0#competition). The challenge evaluates face forgery detection models on the hidden test set.

Besides, the hidden test set will be updated constantly to get future versions along with the development of Deepfakes technology, to better simulates _real-world_ scenarios emphasized in the paper.

**Comment by liquor233** [comment]
Thank u for your quick and clear reply！
